tic
clear
close all
%{
Multi-linear regression for single-PFT Toy Model sites.
%}

%---------------------------  plot essentials  ---------------------------%
if exist('fig_num','var') == 0
    fig_num = 1;
end
GlacialGrey = [0.4 0.7 1];
MagicMaroon = [0.65 0.32 0.35];
EcstaticEmerald = [0.17 0.52 0.5];
GorgeousGold = [1 0.85 0];
BastilleBleu = [0.12 0.34 0.56];
RussianRed = [1 0.032 0.064];
ViolentViolet = [0.6 0 0.7];


%-------------------------------------------------------------------------%
%-----------------------------  import data  -----------------------------%
%-------------------------------------------------------------------------%
load MLRdata_Abisko.mat
load MLRdata_Alptal.mat
load MLRdata_Cherskiy.mat
load MLRdata_Seehornwald.mat
load MLRdata_Sodankyla.mat


%-------------------------------------------------------------------------%
%-------------------------  calculation of bias  -------------------------%
%-------------------------------------------------------------------------%
% calculate LWR from vegetation using vegetation fraction from CLM

% Abisko
LWR_Subcanopy_CLM_Abisko_avg = nan(size(LWR_Atmosphere_Abisko));
LWR_Subcanopy_Observations_Abisko_avg = nan(size(LWR_Atmosphere_Abisko));
for l=1:length(LWR_Atmosphere_Abisko)
    LWR_Subcanopy_CLM_Abisko_avg(l) = mean(LWR_Subcanopy_CLM_Abisko(l,:));
    LWR_Subcanopy_Observations_Abisko_avg(l) = mean(LWR_Subcanopy_Observations_Abisko(l,:));
end
PAI_Abisko_avg = mean(PAI_Abisko);
f_veg = 1 - exp(-PAI_Abisko_avg);
LWR_Vegetation_CLM_Abisko_avg = (LWR_Subcanopy_CLM_Abisko_avg ...
    - (1-f_veg)*LWR_Atmosphere_Abisko)/f_veg;
LWR_Vegetation_Obs_Abisko_avg = (LWR_Subcanopy_Observations_Abisko_avg ...
    - (1-f_veg)*LWR_Atmosphere_Abisko)/f_veg;
LWR_Vegetation_Ratio_Abisko_avg = LWR_Vegetation_CLM_Abisko_avg...
    ./ LWR_Vegetation_Obs_Abisko_avg;
    
% Alptal
f_veg = 1 - exp(-PAI_Alptal);
LWR_Vegetation_CLM_Alptal_2004 = (LWR_Subcanopy_CLM_Alptal_2004 ...
    - (1-f_veg)*LWR_Atmosphere_Alptal_2004)/f_veg;
LWR_Vegetation_Obs_Alptal_2004 = (LWR_Subcanopy_Observations_Alptal_2004 ...
    - (1-f_veg)*LWR_Atmosphere_Alptal_2004)/f_veg;
LWR_Vegetation_Ratio_Alptal_2004 = LWR_Vegetation_CLM_Alptal_2004 ...
    ./ LWR_Vegetation_Obs_Alptal_2004;
LWR_Vegetation_CLM_Alptal_2005 = (LWR_Subcanopy_CLM_Alptal_2005 ...
    - (1-f_veg)*LWR_Atmosphere_Alptal_2005)/f_veg;
LWR_Vegetation_Obs_Alptal_2005 = (LWR_Subcanopy_Observations_Alptal_2005 ...
    - (1-f_veg)*LWR_Atmosphere_Alptal_2005)/f_veg;
LWR_Vegetation_Ratio_Alptal_2005 = LWR_Vegetation_CLM_Alptal_2005 ...
    ./ LWR_Vegetation_Obs_Alptal_2005;
LWR_Vegetation_CLM_Alptal_2006 = (LWR_Subcanopy_CLM_Alptal_2006 ...
    - (1-f_veg)*LWR_Atmosphere_Alptal_2006)/f_veg;
LWR_Vegetation_Obs_Alptal_2006 = (LWR_Subcanopy_Observations_Alptal_2006 ...
    - (1-f_veg)*LWR_Atmosphere_Alptal_2006)/f_veg;
LWR_Vegetation_Ratio_Alptal_2006 = LWR_Vegetation_CLM_Alptal_2006 ...
    ./ LWR_Vegetation_Obs_Alptal_2006;
LWR_Vegetation_CLM_Alptal_2007 = (LWR_Subcanopy_CLM_Alptal_2007 ...
    - (1-f_veg)*LWR_Atmosphere_Alptal_2007)/f_veg;
LWR_Vegetation_Obs_Alptal_2007 = (LWR_Subcanopy_Observations_Alptal_2007 ...
    - (1-f_veg)*LWR_Atmosphere_Alptal_2007)/f_veg;
LWR_Vegetation_Ratio_Alptal_2007 = LWR_Vegetation_CLM_Alptal_2007 ...
    ./ LWR_Vegetation_Obs_Alptal_2007;

% Cherskiy
f_veg = 1 - exp(-PAI_Cherskiy);
LWR_Vegetation_CLM_Cherskiy = (LWR_Subcanopy_CLM_Cherskiy ...
    - (1-f_veg)*LWR_Atmosphere_Cherskiy)/f_veg;
LWR_Vegetation_Obs_Cherskiy = (LWR_Subcanopy_Observations_Cherskiy ...
    - (1-f_veg)*LWR_Atmosphere_Cherskiy)/f_veg;
LWR_Vegetation_Ratio_Cherskiy = LWR_Vegetation_CLM_Cherskiy./LWR_Vegetation_Obs_Cherskiy;

% Seehornwald
f_veg = 1 - exp(-PAI_Seehornwald);
LWR_Vegetation_CLM_Seehornwald_2008 = (LWR_Subcanopy_CLM_Seehornwald_2008 ...
    - (1-f_veg)*LWR_Atmosphere_Seehornwald_2008)/f_veg;
LWR_Vegetation_Obs_Seehornwald_2008 = (LWR_Subcanopy_Observations_Seehornwald_2008 ...
    - (1-f_veg)*LWR_Atmosphere_Seehornwald_2008)/f_veg;
    LWR_Vegetation_Ratio_Seehornwald_2008 = LWR_Vegetation_CLM_Seehornwald_2008...
        ./ LWR_Vegetation_Obs_Seehornwald_2008;
LWR_Vegetation_CLM_Seehornwald_2009 = (LWR_Subcanopy_CLM_Seehornwald_2009 ...
    - (1-f_veg)*LWR_Atmosphere_Seehornwald_2009)/f_veg;
LWR_Vegetation_Obs_Seehornwald_2009 = (LWR_Subcanopy_Observations_Seehornwald_2009 ...
    - (1-f_veg)*LWR_Atmosphere_Seehornwald_2009)/f_veg;
    LWR_Vegetation_Ratio_Seehornwald_2009 = LWR_Vegetation_CLM_Seehornwald_2009...
        ./ LWR_Vegetation_Obs_Seehornwald_2009;
LWR_Vegetation_CLM_Seehornwald_2010 = (LWR_Subcanopy_CLM_Seehornwald_2010 ...
    - (1-f_veg)*LWR_Atmosphere_Seehornwald_2010)/f_veg;
LWR_Vegetation_Obs_Seehornwald_2010 = (LWR_Subcanopy_Observations_Seehornwald_2010 ...
    - (1-f_veg)*LWR_Atmosphere_Seehornwald_2010)/f_veg;
    LWR_Vegetation_Ratio_Seehornwald_2010 = LWR_Vegetation_CLM_Seehornwald_2010...
        ./ LWR_Vegetation_Obs_Seehornwald_2010;
LWR_Vegetation_CLM_Seehornwald_2011 = (LWR_Subcanopy_CLM_Seehornwald_2011 ...
    - (1-f_veg)*LWR_Atmosphere_Seehornwald_2011)/f_veg;
LWR_Vegetation_Obs_Seehornwald_2011 = (LWR_Subcanopy_Observations_Seehornwald_2011 ...
    - (1-f_veg)*LWR_Atmosphere_Seehornwald_2011)/f_veg;
    LWR_Vegetation_Ratio_Seehornwald_2011 = LWR_Vegetation_CLM_Seehornwald_2011...
        ./ LWR_Vegetation_Obs_Seehornwald_2011;
LWR_Vegetation_CLM_Seehornwald_2012 = (LWR_Subcanopy_CLM_Seehornwald_2012 ...
    - (1-f_veg)*LWR_Atmosphere_Seehornwald_2012)/f_veg;
LWR_Vegetation_Obs_Seehornwald_2012 = (LWR_Subcanopy_Observations_Seehornwald_2012 ...
    - (1-f_veg)*LWR_Atmosphere_Seehornwald_2012)/f_veg;
    LWR_Vegetation_Ratio_Seehornwald_2012 = LWR_Vegetation_CLM_Seehornwald_2012...
        ./ LWR_Vegetation_Obs_Seehornwald_2012;
    
% Sodankyla
LWR_Subcanopy_CLM_Sodankyla_avg = nan(size(LWR_Atmosphere_Sodankyla));
LWR_Subcanopy_Observations_Sodankyla_avg = nan(size(LWR_Atmosphere_Sodankyla));
for l=1:length(LWR_Atmosphere_Sodankyla)
    LWR_Subcanopy_CLM_Sodankyla_avg(l) = mean(LWR_Subcanopy_CLM_Sodankyla(l,:));
    LWR_Subcanopy_Observations_Sodankyla_avg(l) ...
        = mean(LWR_Subcanopy_Observations_Sodankyla(l,:));
end
PAI_Sodankyla_avg = mean(PAI_Sodankyla);
f_veg = 1 - exp(-PAI_Sodankyla_avg);
LWR_Vegetation_CLM_Sodankyla_avg = (LWR_Subcanopy_CLM_Sodankyla_avg ...
    - (1-f_veg)*LWR_Atmosphere_Sodankyla)/f_veg;
LWR_Vegetation_Obs_Sodankyla_avg = (LWR_Subcanopy_Observations_Sodankyla_avg ...
    - (1-f_veg)*LWR_Atmosphere_Sodankyla)/f_veg;
LWR_Vegetation_Ratio_Sodankyla_avg = LWR_Vegetation_CLM_Sodankyla_avg...
    ./ LWR_Vegetation_Obs_Sodankyla_avg;


%-------------------------------------------------------------------------%
%-----------------------  multi-linear regression  -----------------------%
%-------------------------------------------------------------------------%

%---------------------  aggregating multiple seasons  ---------------------

% Alptal
Sky_Emissivity_Alptal = vertcat(Sky_Emissivity_Alptal_2004,...
    Sky_Emissivity_Alptal_2005,Sky_Emissivity_Alptal_2006,...
    Sky_Emissivity_Alptal_2007);
SWR_Incoming_Alptal = vertcat(SWR_Incoming_Alptal_2004,...
    SWR_Incoming_Alptal_2005,SWR_Incoming_Alptal_2006,...
    SWR_Incoming_Alptal_2007);
LWR_Vegetation_Ratio_Alptal = vertcat(LWR_Vegetation_Ratio_Alptal_2004,...
    LWR_Vegetation_Ratio_Alptal_2005,LWR_Vegetation_Ratio_Alptal_2006,...
    LWR_Vegetation_Ratio_Alptal_2007);
    
% Seehornwald
    SWR_Incoming_Seehornwald_2012,LWR_Vegetation_Ratio_Seehornwald_2012);
Sky_Emissivity_Seehornwald = vertcat(Sky_Emissivity_Seehornwald_2008,...
    Sky_Emissivity_Seehornwald_2009,Sky_Emissivity_Seehornwald_2010,...
    Sky_Emissivity_Seehornwald_2011,Sky_Emissivity_Seehornwald_2012);
SWR_Incoming_Seehornwald = vertcat(SWR_Incoming_Seehornwald_2008,...
    SWR_Incoming_Seehornwald_2009,SWR_Incoming_Seehornwald_2010,...
    SWR_Incoming_Seehornwald_2011,SWR_Incoming_Seehornwald_2012);
LWR_Vegetation_Ratio_Seehornwald = vertcat(LWR_Vegetation_Ratio_Seehornwald_2008,...
    LWR_Vegetation_Ratio_Seehornwald_2009,LWR_Vegetation_Ratio_Seehornwald_2010,...
    LWR_Vegetation_Ratio_Seehornwald_2011,LWR_Vegetation_Ratio_Seehornwald_2012);

%-----------------  split up into daytime and nighttime  -----------------%
% Abisko
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Abisko)
    if SWR_Incoming_Abisko(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Abisko_Day(idx_day) = SWR_Incoming_Abisko(l);
        Sky_Emissivity_Abisko_Day(idx_day) = Sky_Emissivity_Abisko(l);
        LWR_Vegetation_Ratio_Abisko_avg_Day(idx_day) ...
            = LWR_Vegetation_Ratio_Abisko_avg(l);
    elseif SWR_Incoming_Abisko(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Abisko_Night(idx_night) = SWR_Incoming_Abisko(l);
        Sky_Emissivity_Abisko_Night(idx_night) = Sky_Emissivity_Abisko(l);
        LWR_Vegetation_Ratio_Abisko_avg_Night(idx_night) ...
            = LWR_Vegetation_Ratio_Abisko_avg(l);
    end
end

% Alptal
    % 2004
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Alptal_2004)
    if SWR_Incoming_Alptal_2004(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Alptal_2004_Day(idx_day) ...
            = SWR_Incoming_Alptal_2004(l);
        Sky_Emissivity_Alptal_2004_Day(idx_day) ...
            = Sky_Emissivity_Alptal_2004(l);
        LWR_Vegetation_Ratio_Alptal_2004_Day(idx_day) ...
            = LWR_Vegetation_Ratio_Alptal_2004(l);
    elseif SWR_Incoming_Alptal_2004(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Alptal_2004_Night(idx_night) ...
            =  SWR_Incoming_Alptal_2004(l);
        Sky_Emissivity_Alptal_2004_Night(idx_night) ...
            =  Sky_Emissivity_Alptal_2004(l);
        LWR_Vegetation_Ratio_Alptal_2004_Night(idx_night) ...
            =  LWR_Vegetation_Ratio_Alptal_2004(l);
    end
end
    % 2005
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Alptal_2005)
    if SWR_Incoming_Alptal_2005(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Alptal_2005_Day(idx_day) ...
            =  SWR_Incoming_Alptal_2005(l);
        Sky_Emissivity_Alptal_2005_Day(idx_day) ...
            =  Sky_Emissivity_Alptal_2005(l);
        LWR_Vegetation_Ratio_Alptal_2005_Day(idx_day) ...
            =  LWR_Vegetation_Ratio_Alptal_2005(l);
    elseif SWR_Incoming_Alptal_2005(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Alptal_2005_Night(idx_night) ...
            =  SWR_Incoming_Alptal_2005(l);
        Sky_Emissivity_Alptal_2005_Night(idx_night) ...
            =  Sky_Emissivity_Alptal_2005(l);
        LWR_Vegetation_Ratio_Alptal_2005_Night(idx_night) ...
            =  LWR_Vegetation_Ratio_Alptal_2005(l);
    end
end
    % 2006
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Alptal_2006)
    if SWR_Incoming_Alptal_2006(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Alptal_2006_Day(idx_day) ...
           =  SWR_Incoming_Alptal_2006(l);
        Sky_Emissivity_Alptal_2006_Day(idx_day) ...
           =  Sky_Emissivity_Alptal_2006(l);
        LWR_Vegetation_Ratio_Alptal_2006_Day(idx_day) ...
           =  LWR_Vegetation_Ratio_Alptal_2006(l);
    elseif SWR_Incoming_Alptal_2006(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Alptal_2006_Night(idx_night) ...
           =  SWR_Incoming_Alptal_2006(l);
        Sky_Emissivity_Alptal_2006_Night(idx_night) ...
           =  Sky_Emissivity_Alptal_2006(l);
        LWR_Vegetation_Ratio_Alptal_2006_Night(idx_night) ...
            =  LWR_Vegetation_Ratio_Alptal_2006(l);
    end
end
    % 2007
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Alptal_2007)
    if SWR_Incoming_Alptal_2007(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Alptal_2007_Day(idx_day) ...
           =  SWR_Incoming_Alptal_2007(l);
        Sky_Emissivity_Alptal_2007_Day(idx_day) ...
           =  Sky_Emissivity_Alptal_2007(l);
        LWR_Vegetation_Ratio_Alptal_2007_Day(idx_day) ...
           =  LWR_Vegetation_Ratio_Alptal_2007(l);
    elseif SWR_Incoming_Alptal_2007(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Alptal_2007_Night(idx_night) ...
           =  SWR_Incoming_Alptal_2007(l);
        Sky_Emissivity_Alptal_2007_Night(idx_night) ...
           =  Sky_Emissivity_Alptal_2007(l);
        LWR_Vegetation_Ratio_Alptal_2007_Night(idx_night) ...
           =  LWR_Vegetation_Ratio_Alptal_2007(l);
    end
end
    % total
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Alptal)
    if SWR_Incoming_Alptal(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Alptal_Day(idx_day) ...
           =  SWR_Incoming_Alptal(l);
        Sky_Emissivity_Alptal_Day(idx_day) ...
           =  Sky_Emissivity_Alptal(l);
        LWR_Vegetation_Ratio_Alptal_Day(idx_day) ...
           =  LWR_Vegetation_Ratio_Alptal(l);
    elseif SWR_Incoming_Alptal(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Alptal_Night(idx_night) ...
           =  SWR_Incoming_Alptal(l);
        Sky_Emissivity_Alptal_Night(idx_night) ...
           =  Sky_Emissivity_Alptal(l);
        LWR_Vegetation_Ratio_Alptal_Night(idx_night) ...
           =  LWR_Vegetation_Ratio_Alptal(l);
    end
end

% Cherskiy
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Cherskiy)
    if SWR_Incoming_Cherskiy(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Cherskiy_Day(idx_day) ...
           =  SWR_Incoming_Cherskiy(l);
        Sky_Emissivity_Cherskiy_Day(idx_day) ...
           =  Sky_Emissivity_Cherskiy(l);
        LWR_Vegetation_Ratio_Cherskiy_Day(idx_day) ...
           =  LWR_Vegetation_Ratio_Cherskiy(l);
    elseif SWR_Incoming_Cherskiy(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Cherskiy_Night(idx_night) ...
           =  SWR_Incoming_Cherskiy(l);
        Sky_Emissivity_Cherskiy_Night(idx_night) ...
           =  Sky_Emissivity_Cherskiy(l);
        LWR_Vegetation_Ratio_Cherskiy_Night(idx_night) ...
           =  LWR_Vegetation_Ratio_Cherskiy(l);
    end
end

% Seehornwald
    % 2008
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Seehornwald_2008)
    if SWR_Incoming_Seehornwald_2008(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Seehornwald_2008_Day(idx_day) ...
           =  SWR_Incoming_Seehornwald_2008(l);
        Sky_Emissivity_Seehornwald_2008_Day(idx_day) ...
           =  Sky_Emissivity_Seehornwald_2008(l);
        LWR_Vegetation_Ratio_Seehornwald_2008_Day(idx_day) ...
           =  LWR_Vegetation_Ratio_Seehornwald_2008(l);
    elseif SWR_Incoming_Seehornwald_2008(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Seehornwald_2008_Night(idx_night) ...
           =  SWR_Incoming_Seehornwald_2008(l);
        Sky_Emissivity_Seehornwald_2008_Night(idx_night) ...
           =  Sky_Emissivity_Seehornwald_2008(l);
        LWR_Vegetation_Ratio_Seehornwald_2008_Night(idx_night) ...
           =  LWR_Vegetation_Ratio_Seehornwald_2008(l);
    end
end
    % 2009
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Seehornwald_2009)
    if SWR_Incoming_Seehornwald_2009(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Seehornwald_2009_Day(idx_day) ...
           =  SWR_Incoming_Seehornwald_2009(l);
        Sky_Emissivity_Seehornwald_2009_Day(idx_day) ...
           =  Sky_Emissivity_Seehornwald_2009(l);
        LWR_Vegetation_Ratio_Seehornwald_2009_Day(idx_day) ...
           =  LWR_Vegetation_Ratio_Seehornwald_2009(l);
    elseif SWR_Incoming_Seehornwald_2009(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Seehornwald_2009_Night(idx_night) ...
           =  SWR_Incoming_Seehornwald_2009(l);
        Sky_Emissivity_Seehornwald_2009_Night(idx_night) ...
           =  Sky_Emissivity_Seehornwald_2009(l);
        LWR_Vegetation_Ratio_Seehornwald_2009_Night(idx_night) ...
           =  LWR_Vegetation_Ratio_Seehornwald_2009(l);
    end
end
    % 2010
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Seehornwald_2010)
    if SWR_Incoming_Seehornwald_2010(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Seehornwald_2010_Day(idx_day) ...
           =  SWR_Incoming_Seehornwald_2010(l);
        Sky_Emissivity_Seehornwald_2010_Day(idx_day) ...
           =  Sky_Emissivity_Seehornwald_2010(l);
        LWR_Vegetation_Ratio_Seehornwald_2010_Day(idx_day) ...
           =  LWR_Vegetation_Ratio_Seehornwald_2010(l);
    elseif SWR_Incoming_Seehornwald_2010(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Seehornwald_2010_Night(idx_night) ...
           =  SWR_Incoming_Seehornwald_2010(l);
        Sky_Emissivity_Seehornwald_2010_Night(idx_night) ...
           =  Sky_Emissivity_Seehornwald_2010(l);
        LWR_Vegetation_Ratio_Seehornwald_2010_Night(idx_night) ...
           =  LWR_Vegetation_Ratio_Seehornwald_2010(l);
    end
end
    % 2011
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Seehornwald_2011)
    if SWR_Incoming_Seehornwald_2011(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Seehornwald_2011_Day(idx_day) ...
           =  SWR_Incoming_Seehornwald_2011(l);
        Sky_Emissivity_Seehornwald_2011_Day(idx_day) ...
           =  Sky_Emissivity_Seehornwald_2011(l);
        LWR_Vegetation_Ratio_Seehornwald_2011_Day(idx_day) ...
           =  LWR_Vegetation_Ratio_Seehornwald_2011(l);
    elseif SWR_Incoming_Seehornwald_2011(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Seehornwald_2011_Night(idx_night) ...
           =  SWR_Incoming_Seehornwald_2011(l);
        Sky_Emissivity_Seehornwald_2011_Night(idx_night) ...
           =  Sky_Emissivity_Seehornwald_2011(l);
        LWR_Vegetation_Ratio_Seehornwald_2011_Night(idx_night) ...
           =  LWR_Vegetation_Ratio_Seehornwald_2011(l);
    end
end
    % 2012
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Seehornwald_2012)
    if SWR_Incoming_Seehornwald_2012(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Seehornwald_2012_Day(idx_day) ...
           =  SWR_Incoming_Seehornwald_2012(l);
        Sky_Emissivity_Seehornwald_2012_Day(idx_day) ...
           =  Sky_Emissivity_Seehornwald_2012(l);
        LWR_Vegetation_Ratio_Seehornwald_2012_Day(idx_day) ...
           =  LWR_Vegetation_Ratio_Seehornwald_2012(l);
    elseif SWR_Incoming_Seehornwald_2012(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Seehornwald_2012_Night(idx_night) ...
           =  SWR_Incoming_Seehornwald_2012(l);
        Sky_Emissivity_Seehornwald_2012_Night(idx_night) ...
           =  Sky_Emissivity_Seehornwald_2012(l);
        LWR_Vegetation_Ratio_Seehornwald_2012_Night(idx_night) ...
           =  LWR_Vegetation_Ratio_Seehornwald_2012(l);
    end
end
    % total
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Seehornwald)
    if SWR_Incoming_Seehornwald(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Seehornwald_Day(idx_day) ...
           =  SWR_Incoming_Seehornwald(l);
        Sky_Emissivity_Seehornwald_Day(idx_day) ...
           =  Sky_Emissivity_Seehornwald(l);
        LWR_Vegetation_Ratio_Seehornwald_Day(idx_day) ...
           =  LWR_Vegetation_Ratio_Seehornwald(l);
    elseif SWR_Incoming_Seehornwald(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Seehornwald_Night(idx_night) ...
           =  SWR_Incoming_Seehornwald(l);
        Sky_Emissivity_Seehornwald_Night(idx_night) ...
           =  Sky_Emissivity_Seehornwald(l);
        LWR_Vegetation_Ratio_Seehornwald_Night(idx_night) ...
           =  LWR_Vegetation_Ratio_Seehornwald(l);
    end
end

% Sodankyla
idx_day = 0;
idx_night = 0;
for l=1:length(SWR_Incoming_Sodankyla)
    if SWR_Incoming_Sodankyla(l) > 0
        idx_day = idx_day + 1;
        SWR_Incoming_Sodankyla_Day(idx_day) ...
           =  SWR_Incoming_Sodankyla(l);
        Sky_Emissivity_Sodankyla_Day(idx_day) ...
           =  Sky_Emissivity_Sodankyla(l);
        LWR_Vegetation_Ratio_Sodankyla_avg_Day(idx_day) ...
           =  LWR_Vegetation_Ratio_Sodankyla_avg(l);
    elseif SWR_Incoming_Sodankyla(l) == 0
        idx_night = idx_night + 1;
        SWR_Incoming_Sodankyla_Night(idx_night) ...
           =  SWR_Incoming_Sodankyla(l);
        Sky_Emissivity_Sodankyla_Night(idx_night) ...
           =  Sky_Emissivity_Sodankyla(l);
        LWR_Vegetation_Ratio_Sodankyla_avg_Night(idx_night) ...
           =  LWR_Vegetation_Ratio_Sodankyla_avg(l);
    end
end

%-------------------------------  daytime  -------------------------------%
% Abisko
[Coeffs_Abi_avg_Day,Ints_Abi_avg_Day,Res_Abi_avg_Day,Res_Ints_Abi_avg_Day,Stats_Abi_avg_Day]...
    = MLR_SkySWin(Sky_Emissivity_Abisko_Day',SWR_Incoming_Abisko_Day',...
    LWR_Vegetation_Ratio_Abisko_avg_Day');

% Alptal
[Coeffs_Alp04_Day,Ints_Alp04_Day,Res_Alp04_Day,Res_Ints_Alp04_Day,Stats_Alp04_Day]...
    = MLR_SkySWin(Sky_Emissivity_Alptal_2004_Day',SWR_Incoming_Alptal_2004_Day',...
    LWR_Vegetation_Ratio_Alptal_2004_Day');
[Coeffs_Alp05_Day,Ints_Alp05_Day,Res_Alp05_Day,Res_Ints_Alp05_Day,Stats_Alp05_Day]...
    = MLR_SkySWin(Sky_Emissivity_Alptal_2005_Day',SWR_Incoming_Alptal_2005_Day',...
    LWR_Vegetation_Ratio_Alptal_2005_Day');
[Coeffs_Alp06_Day,Ints_Alp06_Day,Res_Alp06_Day,Res_Ints_Alp06_Day,Stats_Alp06_Day]...
    = MLR_SkySWin(Sky_Emissivity_Alptal_2006_Day',SWR_Incoming_Alptal_2006_Day',...
    LWR_Vegetation_Ratio_Alptal_2006_Day');
[Coeffs_Alp07_Day,Ints_Alp07_Day,Res_Alp07_Day,Res_Ints_Alp07_Day,Stats_Alp07_Day]...
    = MLR_SkySWin(Sky_Emissivity_Alptal_2007_Day',SWR_Incoming_Alptal_2007_Day',...
    LWR_Vegetation_Ratio_Alptal_2007_Day');
Sky_Emissivity_Alptal_Day = horzcat(Sky_Emissivity_Alptal_2004_Day,...
    Sky_Emissivity_Alptal_2005_Day,Sky_Emissivity_Alptal_2006_Day,...
    Sky_Emissivity_Alptal_2007_Day);
SWR_Incoming_Alptal_Day = horzcat(SWR_Incoming_Alptal_2004_Day,...
    SWR_Incoming_Alptal_2005_Day,SWR_Incoming_Alptal_2006_Day,...
    SWR_Incoming_Alptal_2007_Day);
LWR_Vegetation_Ratio_Alptal_Day = horzcat(LWR_Vegetation_Ratio_Alptal_2004_Day,...
    LWR_Vegetation_Ratio_Alptal_2005_Day,LWR_Vegetation_Ratio_Alptal_2006_Day,...
    LWR_Vegetation_Ratio_Alptal_2007_Day);
[Coeffs_Alp_all_Day,Ints_Alp_all_Day,Res_Alp_all_Day,Res_Ints_Alp_all_Day,Stats_Alp_all_Day]...
    = MLR_SkySWin(Sky_Emissivity_Alptal_Day',SWR_Incoming_Alptal_Day',...
    LWR_Vegetation_Ratio_Alptal_Day');

% Cherskiy
[Coeffs_Che_Day,Ints_Che_Day,Res_Che_Day,Res_Ints_Che_Day,Stats_Che_Day]...
    = MLR_SkySWin(Sky_Emissivity_Cherskiy_Day',SWR_Incoming_Cherskiy_Day',...
    LWR_Vegetation_Ratio_Cherskiy_Day');
    
% Seehornwald
[Coeffs_SHW08_Day,Ints_SHW08_Day,Res_SHW08_Day,Res_Ints_SHW08_Day,Stats_SHW08_Day] ...
    = MLR_SkySWin(Sky_Emissivity_Seehornwald_2008_Day',...
    SWR_Incoming_Seehornwald_2008_Day',LWR_Vegetation_Ratio_Seehornwald_2008_Day');
[Coeffs_SHW09_Day,Ints_SHW09_Day,Res_SHW09_Day,Res_Ints_SHW09_Day,Stats_SHW09_Day] ...
    = MLR_SkySWin(Sky_Emissivity_Seehornwald_2009_Day',...
    SWR_Incoming_Seehornwald_2009_Day',LWR_Vegetation_Ratio_Seehornwald_2009_Day');
[Coeffs_SHW10_Day,Ints_SHW10_Day,Res_SHW10_Day,Res_Ints_SHW10_Day,Stats_SHW10_Day] ...
    = MLR_SkySWin(Sky_Emissivity_Seehornwald_2010_Day',...
    SWR_Incoming_Seehornwald_2010_Day',LWR_Vegetation_Ratio_Seehornwald_2010_Day');
[Coeffs_SHW11_Day,Ints_SHW11_Day,Res_SHW11_Day,Res_Ints_SHW11_Day,Stats_SHW11_Day] ...
    = MLR_SkySWin(Sky_Emissivity_Seehornwald_2011_Day',...
    SWR_Incoming_Seehornwald_2011_Day',LWR_Vegetation_Ratio_Seehornwald_2011_Day');
[Coeffs_SHW12_Day,Ints_SHW12_Day,Res_SHW012_Day,Res_Ints_SHW12_Day,Stats_SHW12_Day] ...
    = MLR_SkySWin(Sky_Emissivity_Seehornwald_2012_Day',...
    SWR_Incoming_Seehornwald_2012_Day',LWR_Vegetation_Ratio_Seehornwald_2012_Day');
Sky_Emissivity_Seehornwald_Day = horzcat(Sky_Emissivity_Seehornwald_2008_Day,...
    Sky_Emissivity_Seehornwald_2009_Day,Sky_Emissivity_Seehornwald_2010_Day,...
    Sky_Emissivity_Seehornwald_2011_Day,Sky_Emissivity_Seehornwald_2012_Day);
SWR_Incoming_Seehornwald_Day = horzcat(SWR_Incoming_Seehornwald_2008_Day,...
    SWR_Incoming_Seehornwald_2009_Day,SWR_Incoming_Seehornwald_2010_Day,...
    SWR_Incoming_Seehornwald_2011_Day,SWR_Incoming_Seehornwald_2012_Day);
LWR_Vegetation_Ratio_Seehornwald_Day = horzcat(LWR_Vegetation_Ratio_Seehornwald_2008_Day,...
    LWR_Vegetation_Ratio_Seehornwald_2009_Day,LWR_Vegetation_Ratio_Seehornwald_2010_Day,...
    LWR_Vegetation_Ratio_Seehornwald_2011_Day,LWR_Vegetation_Ratio_Seehornwald_2012_Day);
[Coeffs_SHW_all_Day,Ints_SHW_all_Day,Res_SHW_all_Day,Res_Ints_SHW_all_Day,Stats_SHW_all_Day] ...
    = MLR_SkySWin(Sky_Emissivity_Seehornwald_Day',SWR_Incoming_Seehornwald_Day',...
    LWR_Vegetation_Ratio_Seehornwald_Day');

% Sodankyla
[Coeffs_Sod_avg_Day,Ints_Sod_avg_Day,Res_Sod_avg_Day,Res_Ints_Sod_avg_Day,Stats_Sod_avg_Day]...
    = MLR_SkySWin(Sky_Emissivity_Sodankyla_Day',SWR_Incoming_Sodankyla_Day',...
    LWR_Vegetation_Ratio_Sodankyla_avg_Day');

%------------------------------  nighttime  ------------------------------%
% Abisko
[Coeffs_Abi_avg_Night,Ints_Abi_avg_Night,Res_Abi_avg_Night,...
    Res_Ints_Abi_avg_Night,Stats_Abi_avg_Night]...
    = MLR_SkySWin(Sky_Emissivity_Abisko_Night',SWR_Incoming_Abisko_Night',...
    LWR_Vegetation_Ratio_Abisko_avg_Night');

% Alptal
[Coeffs_Alp04_Night,Ints_Alp04_Night,Res_Alp04_Night,...
    Res_Ints_Alp04_Night,Stats_Alp04_Night]...
    = MLR_SkySWin(Sky_Emissivity_Alptal_2004_Night',...
    SWR_Incoming_Alptal_2004_Night',LWR_Vegetation_Ratio_Alptal_2004_Night');
[Coeffs_Alp05_Night,Ints_Alp05_Night,Res_Alp05_Night,...
    Res_Ints_Alp05_Night,Stats_Alp05_Night]...
    = MLR_SkySWin(Sky_Emissivity_Alptal_2005_Night',...
    SWR_Incoming_Alptal_2005_Night',LWR_Vegetation_Ratio_Alptal_2005_Night');
[Coeffs_Alp06_Night,Ints_Alp06_Night,Res_Alp06_Night,...
    Res_Ints_Alp06_Night,Stats_Alp06_Night]...
    = MLR_SkySWin(Sky_Emissivity_Alptal_2006_Night',...
    SWR_Incoming_Alptal_2006_Night',LWR_Vegetation_Ratio_Alptal_2006_Night');
[Coeffs_Alp07_Night,Ints_Alp07_Night,Res_Alp07_Night,...
    Res_Ints_Alp07_Night,Stats_Alp07_Night]...
    = MLR_SkySWin(Sky_Emissivity_Alptal_2007_Night',...
    SWR_Incoming_Alptal_2007_Night',LWR_Vegetation_Ratio_Alptal_2007_Night');
Sky_Emissivity_Alptal_Night = horzcat(Sky_Emissivity_Alptal_2004_Night,...
    Sky_Emissivity_Alptal_2005_Night,Sky_Emissivity_Alptal_2006_Night,...
    Sky_Emissivity_Alptal_2007_Night);
SWR_Incoming_Alptal_Night = horzcat(SWR_Incoming_Alptal_2004_Night,...
    SWR_Incoming_Alptal_2005_Night,SWR_Incoming_Alptal_2006_Night,...
    SWR_Incoming_Alptal_2007_Night);
LWR_Vegetation_Ratio_Alptal_Night = horzcat(LWR_Vegetation_Ratio_Alptal_2004_Night,...
    LWR_Vegetation_Ratio_Alptal_2005_Night,LWR_Vegetation_Ratio_Alptal_2006_Night,...
    LWR_Vegetation_Ratio_Alptal_2007_Night);
[Coeffs_Alp_all_Night,Ints_Alp_all_Night,Res_Alp_all_Night,...
    Res_Ints_Alp_all_Night,Stats_Alp_all_Night]...
    = MLR_SkySWin(Sky_Emissivity_Alptal_Night',SWR_Incoming_Alptal_Night',...
    LWR_Vegetation_Ratio_Alptal_Night');

% Cherskiy
[Coeffs_Che_Night,Ints_Che_Night,Res_Che_Night,Res_Ints_Che_Night,Stats_Che_Night]...
    = MLR_SkySWin(Sky_Emissivity_Cherskiy_Night',SWR_Incoming_Cherskiy_Night',...
    LWR_Vegetation_Ratio_Cherskiy_Night');
    
% Seehornwald
[Coeffs_SHW08_Night,Ints_SHW08_Night,Res_SHW08_Night,...
    Res_Ints_SHW08_Night,Stats_SHW08_Night] ...
    = MLR_SkySWin(Sky_Emissivity_Seehornwald_2008_Night',...
    SWR_Incoming_Seehornwald_2008_Night',LWR_Vegetation_Ratio_Seehornwald_2008_Night');
[Coeffs_SHW09_Night,Ints_SHW09_Night,Res_SHW09_Night,...
    Res_Ints_SHW09_Night,Stats_SHW09_Night] ...
    = MLR_SkySWin(Sky_Emissivity_Seehornwald_2009_Night',...
    SWR_Incoming_Seehornwald_2009_Night',LWR_Vegetation_Ratio_Seehornwald_2009_Night');
[Coeffs_SHW10_Night,Ints_SHW10_Night,Res_SHW10_Night,...
    Res_Ints_SHW10_Night,Stats_SHW10_Night] ...
    = MLR_SkySWin(Sky_Emissivity_Seehornwald_2010_Night',...
    SWR_Incoming_Seehornwald_2010_Night',LWR_Vegetation_Ratio_Seehornwald_2010_Night');
[Coeffs_SHW11_Night,Ints_SHW11_Night,Res_SHW11_Night,...
    Res_Ints_SHW11_Night,Stats_SHW11_Night] ...
    = MLR_SkySWin(Sky_Emissivity_Seehornwald_2011_Night',...
    SWR_Incoming_Seehornwald_2011_Night',LWR_Vegetation_Ratio_Seehornwald_2011_Night');
[Coeffs_SHW12_Night,Ints_SHW12_Night,Res_SHW012_Night,...
    Res_Ints_SHW12_Night,Stats_SHW12_Night] ...
    = MLR_SkySWin(Sky_Emissivity_Seehornwald_2012_Night',...
    SWR_Incoming_Seehornwald_2012_Night',LWR_Vegetation_Ratio_Seehornwald_2012_Night');
Sky_Emissivity_Seehornwald_Night = horzcat(Sky_Emissivity_Seehornwald_2008_Night,...
    Sky_Emissivity_Seehornwald_2009_Night,Sky_Emissivity_Seehornwald_2010_Night,...
    Sky_Emissivity_Seehornwald_2011_Night,Sky_Emissivity_Seehornwald_2012_Night);
SWR_Incoming_Seehornwald_Night = horzcat(SWR_Incoming_Seehornwald_2008_Night,...
    SWR_Incoming_Seehornwald_2009_Night,SWR_Incoming_Seehornwald_2010_Night,...
    SWR_Incoming_Seehornwald_2011_Night,SWR_Incoming_Seehornwald_2012_Night);
LWR_Vegetation_Ratio_Seehornwald_Night = horzcat(LWR_Vegetation_Ratio_Seehornwald_2008_Night,...
    LWR_Vegetation_Ratio_Seehornwald_2009_Night,LWR_Vegetation_Ratio_Seehornwald_2010_Night,...
    LWR_Vegetation_Ratio_Seehornwald_2011_Night,LWR_Vegetation_Ratio_Seehornwald_2012_Night);
[Coeffs_SHW_all_Night,Ints_SHW_all_Night,Res_SHW_all_Night,...
    Res_Ints_SHW_all_Night,Stats_SHW_all_Night] ...
    = MLR_SkySWin(Sky_Emissivity_Seehornwald_Night',...
    SWR_Incoming_Seehornwald_Night',LWR_Vegetation_Ratio_Seehornwald_Night');

% Sodankyla
[Coeffs_Sod_avg_Night,Ints_Sod_avg_Night,Res_Sod_avg_Night,...
    Res_Ints_Sod_avg_Night,Stats_Sod_avg_Night]...
    = MLR_SkySWin(Sky_Emissivity_Sodankyla_Night',...
    SWR_Incoming_Sodankyla_Night',LWR_Vegetation_Ratio_Sodankyla_avg_Night');


%-------------------  aggregating sites for correction  -------------------
%{
Alptal + Cherskiy + Sodankyla + Seehornwald
To avoid imbalance in site data, we use one season for each Alptal and
Seehornwald. The particular years are chosen based on previous MLRs (see
above) so that the chosen years are as close as possible to the MLR results
for all years combined.
%}
Sky_Emissivity_Super = horzcat(Sky_Emissivity_Alptal_2005',...
    Sky_Emissivity_Cherskiy,Sky_Emissivity_Sodankyla',...
    Sky_Emissivity_Seehornwald_2009');
Sky_Emissivity_Super_Day = horzcat(Sky_Emissivity_Alptal_2005_Day,...
    Sky_Emissivity_Cherskiy_Day,Sky_Emissivity_Sodankyla_Day,...
    Sky_Emissivity_Seehornwald_2009_Day);
Sky_Emissivity_Super_Night = horzcat(Sky_Emissivity_Alptal_2005_Night,...
    Sky_Emissivity_Cherskiy_Night,Sky_Emissivity_Sodankyla_Night,...
    Sky_Emissivity_Seehornwald_2009_Night);
SWR_Incoming_Super = horzcat(SWR_Incoming_Alptal_2005',...
    SWR_Incoming_Cherskiy,SWR_Incoming_Sodankyla,...
    SWR_Incoming_Seehornwald_2009');
SWR_Incoming_Super_Day = horzcat(SWR_Incoming_Alptal_2005_Day,...
    SWR_Incoming_Cherskiy_Day,SWR_Incoming_Sodankyla_Day,...
    SWR_Incoming_Seehornwald_2009_Day);
SWR_Incoming_Super_Night = horzcat(SWR_Incoming_Alptal_2005_Night,...
    SWR_Incoming_Cherskiy_Night,SWR_Incoming_Sodankyla_Night,...
    SWR_Incoming_Seehornwald_2009_Night);
LWR_Vegetation_Ratio_Super = horzcat(LWR_Vegetation_Ratio_Alptal_2005',...
    LWR_Vegetation_Ratio_Cherskiy,LWR_Vegetation_Ratio_Sodankyla_avg,...
    LWR_Vegetation_Ratio_Seehornwald_2009');
LWR_Vegetation_Ratio_Super_Day = horzcat(LWR_Vegetation_Ratio_Alptal_2005_Day,...
    LWR_Vegetation_Ratio_Cherskiy_Day,LWR_Vegetation_Ratio_Sodankyla_avg_Day,...
    LWR_Vegetation_Ratio_Seehornwald_2009_Day);
LWR_Vegetation_Ratio_Super_Night = horzcat(LWR_Vegetation_Ratio_Alptal_2005_Night,...
    LWR_Vegetation_Ratio_Cherskiy_Night,LWR_Vegetation_Ratio_Sodankyla_avg_Night,...
    LWR_Vegetation_Ratio_Seehornwald_2009_Night);

[Coeffs_Super,Ints_Super,Res_Super,Res_Ints_Super,Stats_Super]...
    = MLR_SkySWin(Sky_Emissivity_Super',SWR_Incoming_Super',...
    LWR_Vegetation_Ratio_Super');
[Coeffs_Super_Day,Ints_Super_Day,Res_Super_Day,...
    Res_Ints_Super_Day,Stats_Super_Day]...
    = MLR_SkySWin(Sky_Emissivity_Super_Day',SWR_Incoming_Super_Day',...
    LWR_Vegetation_Ratio_Super_Day');
[Coeffs_Super_Night,Ints_Super_Night,Res_Super_Night,...
    Res_Ints_Super_Night,Stats_Super_Night]...
    = MLR_SkySWin(Sky_Emissivity_Super_Night',SWR_Incoming_Super_Night',...
    LWR_Vegetation_Ratio_Super_Night');


%----------------------------  visualization  ----------------------------%

fig=figure(fig_num);fig_num = fig_num+1;
set(gcf,'Position',get(0,'ScreenSize'))
sp1 = subplot(2,3,1);
hold on
text(0+0.05*6,0.7+0.95*0.6,'a','FontSize',15,'FontWeight','bold')
plot([0 6],[1 1],':k')
% plot([0 6],[0.7582 0.7582],':r')
plot([0 6],[Coeffs_Super_Night(1) Coeffs_Super_Night(1)],'r')
plot([PAI_Abisko_avg PAI_Abisko_avg],Ints_Abi_avg_Night(1,:),'Color',GorgeousGold)
plot([PAI_Alptal PAI_Alptal],Ints_Alp_all_Night(1,:),'Color',EcstaticEmerald)
plot([PAI_Cherskiy PAI_Cherskiy],Ints_Che_Night(1,:),'Color',BastilleBleu)
plot([PAI_Seehornwald PAI_Seehornwald],Ints_SHW_all_Night(1,:),'Color',MagicMaroon)
plot([PAI_Sodankyla_avg PAI_Sodankyla_avg],Ints_Sod_avg_Night(1,:),'Color',GlacialGrey)
% plot([PAI_Yakutsk PAI_Yakutsk],Ints_Yak_Night(1,:),'Color',ViolentViolet)
abi=plot(PAI_Abisko_avg,Coeffs_Abi_avg_Night(1),'MarkerEdgeColor',GorgeousGold,...
    'MarkerFaceColor',GorgeousGold,'Marker','o','MarkerSize',10,'LineStyle','none');
alp=plot(PAI_Alptal,Coeffs_Alp_all_Night(1),'MarkerEdgeColor',EcstaticEmerald,...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',10,'LineStyle','none');
che=plot(PAI_Cherskiy,Coeffs_Che_Night(1),'MarkerEdgeColor',BastilleBleu,...
    'MarkerFaceColor',BastilleBleu,'Marker','o','MarkerSize',10,'LineStyle','none');
shw=plot(PAI_Seehornwald,Coeffs_SHW_all_Night(1),'MarkerEdgeColor',MagicMaroon,...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',10,'LineStyle','none');
sod=plot(PAI_Sodankyla_avg,Coeffs_Sod_avg_Night(1),'MarkerEdgeColor',GlacialGrey,...
    'MarkerFaceColor',GlacialGrey,'Marker','o','MarkerSize',10,'LineStyle','none');
% plot(PAI_Yakutsk,Coeffs_Yak_Night(1),'MarkerEdgeColor',ViolentViolet,...
%     'MarkerFaceColor',ViolentViolet,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp04_Night(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp05_Night(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp06_Night(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp07_Night(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW08_Night(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW09_Night(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW10_Night(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW11_Night(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW12_Night(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
hold off
ylim([0.7 1.3])
% xlabel('PAI [m^2 m^{-2}]','FontSize',12,'FontWeight','bold')
ylabel('Regression Coefficient','FontSize',15,'FontWeight','bold')
title('Night, Intercept (b_0)','FontSize',15,'FontWeight','bold')
set(gca,'FontSize',15,'FontWeight','bold','LineWidth',2)
leg=legend([abi,alp,che,shw,sod],...
    'Abisko','Alptal','Cherskiy','Seehornwald','Sodankylä',...
    'location','northeast','orientation','vertical');
legend('boxoff')
set(leg,'position',[0.19,0.815,0.13,0.13])
box on
sp2 = subplot(2,3,2);
hold on
text(0+0.05*6,0.7+0.95*0.6,'b','FontSize',15,'FontWeight','bold')
plot([0 6],[1 1],':k')
% plot([0 6],[0.8668 0.8668],':r')  % inverse effective emissivity of the sky
% plot([0 6],[0.8685 0.8685],':r')
plot([0 6],[Coeffs_Super_Day(1) Coeffs_Super_Day(1)],'r')
plot([PAI_Abisko_avg PAI_Abisko_avg],Ints_Abi_avg_Day(1,:),'Color',GorgeousGold)
plot([PAI_Alptal PAI_Alptal],Ints_Alp_all_Day(1,:),'Color',EcstaticEmerald)
plot([PAI_Cherskiy PAI_Cherskiy],Ints_Che_Day(1,:),'Color',BastilleBleu)
plot([PAI_Seehornwald PAI_Seehornwald],Ints_SHW_all_Day(1,:),'Color',MagicMaroon)
plot([PAI_Sodankyla_avg PAI_Sodankyla_avg],Ints_Sod_avg_Day(1,:),'Color',GlacialGrey)
plot(PAI_Abisko_avg,Coeffs_Abi_avg_Day(1),'MarkerEdgeColor',GorgeousGold,...
    'MarkerFaceColor',GorgeousGold,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp_all_Day(1),'MarkerEdgeColor',EcstaticEmerald,...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Cherskiy,Coeffs_Che_Day(1),'MarkerEdgeColor',BastilleBleu,...
    'MarkerFaceColor',BastilleBleu,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW_all_Day(1),'MarkerEdgeColor',MagicMaroon,...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Sodankyla_avg,Coeffs_Sod_avg_Day(1),'MarkerEdgeColor',GlacialGrey,...
    'MarkerFaceColor',GlacialGrey,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp04_Day(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp05_Day(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp06_Day(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp07_Day(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW08_Day(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW09_Day(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW10_Day(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW11_Day(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW12_Day(1),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
hold off
ylim([0.7 1.3])
% xlabel('PAI [m^2 m^{-2}]','FontSize',15,'FontWeight','bold')
% ylabel('Regression Coefficient b_0','FontSize',15,'FontWeight','bold')
title('Day, Intercept (b_0)','FontSize',15,'FontWeight','bold')
set(gca,'FontSize',15,'FontWeight','bold','LineWidth',2)
box on
sp3 = subplot(2,3,3);
hold on
text(0+0.05*6,-1*10^(-3)+0.95*2*10^(-3),'c','FontSize',15,'FontWeight','bold')
plot([0 6],[0 0],':k')
% plot([0 6],[-5.4812*10^(-5) -5.4812*10^(-5)],':r')  % inverse effective emissivity of the sky
% plot([0 6],[5.2627*10^(-4) 5.2627*10^(-4)],':r')
plot([0 6],[Coeffs_Super_Day(3) Coeffs_Super_Day(3)],'r')
plot([PAI_Abisko_avg PAI_Abisko_avg],Ints_Abi_avg_Day(3,:),'Color',GorgeousGold)
plot([PAI_Alptal PAI_Alptal],Ints_Alp_all_Day(3,:),'Color',EcstaticEmerald)
plot([PAI_Cherskiy PAI_Cherskiy],Ints_Che_Day(3,:),'Color',BastilleBleu)
plot([PAI_Seehornwald PAI_Seehornwald],Ints_SHW_all_Day(3,:),'Color',MagicMaroon)
plot([PAI_Sodankyla_avg PAI_Sodankyla_avg],Ints_Sod_avg_Day(3,:),'Color',GlacialGrey)
plot(PAI_Abisko_avg,Coeffs_Abi_avg_Day(3),'MarkerEdgeColor',GorgeousGold,...
    'MarkerFaceColor',GorgeousGold,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp_all_Day(3),'MarkerEdgeColor',EcstaticEmerald,...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Cherskiy,Coeffs_Che_Day(3),'MarkerEdgeColor',BastilleBleu,...
    'MarkerFaceColor',BastilleBleu,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW_all_Day(3),'MarkerEdgeColor',MagicMaroon,...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Sodankyla_avg,Coeffs_Sod_avg_Day(3),'MarkerEdgeColor',GlacialGrey,...
    'MarkerFaceColor',GlacialGrey,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp04_Day(3),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp05_Day(3),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp06_Day(3),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp07_Day(3),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW08_Day(3),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW09_Day(3),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW10_Day(3),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW11_Day(3),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW12_Day(3),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
hold off
ylim([-1*10^(-3) 1*10^(-3)])
set(gca,'YTick',-1*10^(-3):0.2*10^(-3):1*10^(-3))
% xlabel('PAI [m^2 m^{-2}]','FontSize',15,'FontWeight','bold')
% ylabel('Regression Coefficient b_2','FontSize',15,'FontWeight','bold')
title('Day, Insolation (b_2)','FontSize',15,'FontWeight','bold')
set(gca,'FontSize',15,'FontWeight','bold','LineWidth',2)
box on
sp4 = subplot(2,3,4);
hold on
text(0+0.05*6,-0.4+0.95*0.8,'d','FontSize',15,'FontWeight','bold')
plot([0 6],[0 0],':k')
% plot([0 6],[0.2342 0.2342],':r')
plot([0 6],[Coeffs_Super_Night(2) Coeffs_Super_Night(2)],'r')
plot([PAI_Abisko_avg PAI_Abisko_avg],Ints_Abi_avg_Night(2,:),'Color',GorgeousGold)
plot([PAI_Alptal PAI_Alptal],Ints_Alp_all_Night(2,:),'Color',EcstaticEmerald)
plot([PAI_Cherskiy PAI_Cherskiy],Ints_Che_Night(2,:),'Color',BastilleBleu)
plot([PAI_Seehornwald PAI_Seehornwald],Ints_SHW_all_Night(2,:),'Color',MagicMaroon)
plot([PAI_Sodankyla_avg PAI_Sodankyla_avg],Ints_Sod_avg_Night(2,:),'Color',GlacialGrey)
% plot([PAI_Yakutsk PAI_Yakutsk],Ints_Yak_Night(2,:),'Color',ViolentViolet)
abi=plot(PAI_Abisko_avg,Coeffs_Abi_avg_Night(2),'MarkerEdgeColor',GorgeousGold,...
    'MarkerFaceColor',GorgeousGold,'Marker','o','MarkerSize',10,'LineStyle','none');
alp=plot(PAI_Alptal,Coeffs_Alp_all_Night(2),'MarkerEdgeColor',EcstaticEmerald,...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',10,'LineStyle','none');
che=plot(PAI_Cherskiy,Coeffs_Che_Night(2),'MarkerEdgeColor',BastilleBleu,...
    'MarkerFaceColor',BastilleBleu,'Marker','o','MarkerSize',10,'LineStyle','none');
shw=plot(PAI_Seehornwald,Coeffs_SHW_all_Night(2),'MarkerEdgeColor',MagicMaroon,...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',10,'LineStyle','none');
sod=plot(PAI_Sodankyla_avg,Coeffs_Sod_avg_Night(2),'MarkerEdgeColor',GlacialGrey,...
    'MarkerFaceColor',GlacialGrey,'Marker','o','MarkerSize',10,'LineStyle','none');
% plot(PAI_Yakutsk,Coeffs_Yak_Night(2),'MarkerEdgeColor',ViolentViolet,...
%     'MarkerFaceColor',ViolentViolet,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp04_Night(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp05_Night(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp06_Night(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp07_Night(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW08_Night(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW09_Night(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW10_Night(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW11_Night(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW12_Night(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
hold off
ylim([-0.4 0.4])
xlabel('PAI [m^2 m^{-2}]','FontSize',15,'FontWeight','bold')
ylabel('Regression Coefficient','FontSize',15,'FontWeight','bold')
title('Night, Sky Emissivity (b_1)','FontSize',15,'FontWeight','bold')
set(gca,'YTick',-0.4:0.1:0.4,'FontSize',15,'FontWeight','bold','LineWidth',2)
box on
sp5 = subplot(2,3,5);
hold on
text(0+0.05*6,-0.4+0.95*0.8,'e','FontSize',15,'FontWeight','bold')
plot([0 6],[0 0],':k')
% plot([0 6],[0.1240 0.1240],':r')  % inverse effective emissivity of the sky
% plot([0 6],[0.1223 0.1223],':r')
plot([0 6],[Coeffs_Super_Day(2) Coeffs_Super_Day(2)],'r')
plot([PAI_Abisko_avg PAI_Abisko_avg],Ints_Abi_avg_Day(2,:),'Color',GorgeousGold)
plot([PAI_Alptal PAI_Alptal],Ints_Alp_all_Day(2,:),'Color',EcstaticEmerald)
plot([PAI_Cherskiy PAI_Cherskiy],Ints_Che_Day(2,:),'Color',BastilleBleu)
plot([PAI_Seehornwald PAI_Seehornwald],Ints_SHW_all_Day(2,:),'Color',MagicMaroon)
plot([PAI_Sodankyla_avg PAI_Sodankyla_avg],Ints_Sod_avg_Day(2,:),'Color',GlacialGrey)
plot(PAI_Abisko_avg,Coeffs_Abi_avg_Day(2),'MarkerEdgeColor',GorgeousGold,...
    'MarkerFaceColor',GorgeousGold,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp_all_Day(2),'MarkerEdgeColor',EcstaticEmerald,...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Cherskiy,Coeffs_Che_Day(2),'MarkerEdgeColor',BastilleBleu,...
    'MarkerFaceColor',BastilleBleu,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW_all_Day(2),'MarkerEdgeColor',MagicMaroon,...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Sodankyla_avg,Coeffs_Sod_avg_Day(2),'MarkerEdgeColor',GlacialGrey,...
    'MarkerFaceColor',GlacialGrey,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp04_Day(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp05_Day(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp06_Day(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp07_Day(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW08_Day(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW09_Day(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW10_Day(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW11_Day(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW12_Day(2),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
hold off
ylim([-0.4 0.4])
xlabel('PAI [m^2 m^{-2}]','FontSize',15,'FontWeight','bold')
% ylabel('Regression Coefficient b_1','FontSize',15,'FontWeight','bold')
title('Day, Sky Emissivity (b_1)','FontSize',15,'FontWeight','bold')
set(gca,'YTick',-0.4:0.1:0.4,'FontSize',15,'FontWeight','bold','LineWidth',2)
box on
sp6 = subplot(2,3,6);
hold on
text(0+0.05*6,-1*10^(-3)+0.95*2*10^(-3),'f','FontSize',15,'FontWeight','bold')
plot([0 6],[0 0],':k')
% plot([0 6],[2.2885*10^(-4) 2.2885*10^(-4)],':r')  % inverse effective emissivity of the sky
% plot([0 6],[-3.6065*10^(-4) -3.6065*10^(-4)],':r')
plot([0 6],[Coeffs_Super_Day(4) Coeffs_Super_Day(4)],'r')
plot([PAI_Abisko_avg PAI_Abisko_avg],Ints_Abi_avg_Day(4,:),'Color',GorgeousGold)
plot([PAI_Alptal PAI_Alptal],Ints_Alp_all_Day(4,:),'Color',EcstaticEmerald)
plot([PAI_Cherskiy PAI_Cherskiy],Ints_Che_Day(4,:),'Color',BastilleBleu)
plot([PAI_Seehornwald PAI_Seehornwald],Ints_SHW_all_Day(4,:),'Color',MagicMaroon)
plot([PAI_Sodankyla_avg PAI_Sodankyla_avg],Ints_Sod_avg_Day(4,:),'Color',GlacialGrey)
plot(PAI_Abisko_avg,Coeffs_Abi_avg_Day(4),'MarkerEdgeColor',GorgeousGold,...
    'MarkerFaceColor',GorgeousGold,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp_all_Day(4),'MarkerEdgeColor',EcstaticEmerald,...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Cherskiy,Coeffs_Che_Day(4),'MarkerEdgeColor',BastilleBleu,...
    'MarkerFaceColor',BastilleBleu,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW_all_Day(4),'MarkerEdgeColor',MagicMaroon,...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Sodankyla_avg,Coeffs_Sod_avg_Day(4),'MarkerEdgeColor',GlacialGrey,...
    'MarkerFaceColor',GlacialGrey,'Marker','o','MarkerSize',10,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp04_Day(4),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp05_Day(4),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp06_Day(4),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Alptal,Coeffs_Alp07_Day(4),'MarkerEdgeColor','k',...
    'MarkerFaceColor',EcstaticEmerald,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW08_Day(4),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW09_Day(4),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW10_Day(4),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW11_Day(4),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
plot(PAI_Seehornwald,Coeffs_SHW12_Day(4),'MarkerEdgeColor','k',...
    'MarkerFaceColor',MagicMaroon,'Marker','o','MarkerSize',5,'LineStyle','none')
hold off
ylim([-1*10^(-3) 1*10^(-3)])
set(gca,'YTick',-1*10^(-3):0.2*10^(-3):1*10^(-3))
xlabel('PAI [m^2 m^{-2}]','FontSize',15,'FontWeight','bold')
% ylabel('Regression Coefficient b_3','FontSize',15,'FontWeight','bold')
title('Day, Interaction (b_3)','FontSize',15,'FontWeight','bold')
set(gca,'FontSize',15,'FontWeight','bold','LineWidth',2)
box on
% positioning & print
set(sp1,'Position',[0.06,0.57,0.27,0.39])
set(sp2,'Position',[0.39,0.57,0.27,0.39])
set(sp3,'Position',[0.72,0.57,0.27,0.39])
set(sp4,'Position',[0.06,0.08,0.27,0.39])
set(sp5,'Position',[0.39,0.08,0.27,0.39])
set(sp6,'Position',[0.72,0.08,0.27,0.39])
fig.PaperUnits = 'inches';
fig.PaperPosition = [0 0 11.7 8.3]; % A4
fig.PaperSize = [11.7 8.3]; % A4
print(fig,'-dpng','-r600','MLR_Coefficients_Paper.png')
print(fig,'-dpdf','-r600','MLR_Coefficients_Paper.pdf')

toc